SUPABASE_URL = "https://vvdracgofuligdqnusvp.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2ZHJhY2dvZnVsaWdkcW51c3ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwNTMwMTQsImV4cCI6MjA4NjYyOTAxNH0.U27UD27hETeL7SkesflliVQa5hV9GSF06_rKgR-IjdM"
